import { BadgeType } from "./badge";

export interface Product {
  id: number;
  name: string;
  price: string;
  badge: BadgeType;
  color: string;
  icon: string;
}

export const products: Product[] = [
  // Fruits
  {
    id: 1,
    name: "Fresh Mango (Alphonso)",
    price: "S$1.30/kg",
    badge: "Fruits",
    color: "from-yellow-300 to-orange-400",
    icon: "🥭",
  },
  {
    id: 2,
    name: "Sweet Guava",
    price: "S$0.65/kg",
    badge: "Fruits",
    color: "from-green-200 to-green-400",
    icon: "🍈",
  },
  {
    id: 3,
    name: "Fresh Pomegranate",
    price: "S$1.95/kg",
    badge: "Fruits",
    color: "from-red-300 to-red-500",
    icon: "🍎",
  },
  {
    id: 4,
    name: "Kesar Banana",
    price: "S$0.95/dozen",
    badge: "Fruits",
    color: "from-yellow-200 to-yellow-400",
    icon: "🍌",
  },
  {
    id: 5,
    name: "Fresh Papaya",
    price: "S$0.50/kg",
    badge: "Fruits",
    color: "from-orange-200 to-orange-400",
    icon: "🍊",
  },

  // Vegetables
  {
    id: 6,
    name: "Lady Finger (Bhindi)",
    price: "S$0.65/kg",
    badge: "Vegetables",
    color: "from-green-300 to-green-500",
    icon: "🥒",
  },
  {
    id: 7,
    name: "Brinjal (Baingan)",
    price: "S$0.55/kg",
    badge: "Vegetables",
    color: "from-purple-300 to-purple-500",
    icon: "🍆",
  },
  {
    id: 8,
    name: "Bitter Gourd (Karela)",
    price: "S$0.75/kg",
    badge: "Vegetables",
    color: "from-green-400 to-green-600",
    icon: "🥬",
  },
  {
    id: 9,
    name: "Bottle Gourd (Lauki)",
    price: "S$0.40/kg",
    badge: "Vegetables",
    color: "from-green-200 to-green-400",
    icon: "🥒",
  },
  {
    id: 10,
    name: "Drumstick (Moringa)",
    price: "S$0.95/kg",
    badge: "Vegetables",
    color: "from-green-300 to-green-500",
    icon: "🌿",
  },

  // Beverages
  {
    id: 11,
    name: "Coca Cola 600ml",
    price: "S$0.65",
    badge: "Beverages",
    color: "from-red-400 to-red-600",
    icon: "🥤",
  },
  {
    id: 12,
    name: "Pepsi 600ml",
    price: "S$0.65",
    badge: "Beverages",
    color: "from-blue-400 to-blue-600",
    icon: "🥤",
  },
  {
    id: 13,
    name: "Thums Up 600ml",
    price: "S$0.65",
    badge: "Beverages",
    color: "from-gray-600 to-gray-800",
    icon: "🥤",
  },
  {
    id: 14,
    name: "Masala Chai",
    price: "S$0.25/cup",
    badge: "Beverages",
    color: "from-amber-300 to-amber-500",
    icon: "☕",
  },
  {
    id: 15,
    name: "Sweet Lassi",
    price: "S$0.50",
    badge: "Dairy",
    color: "from-pink-200 to-pink-400",
    icon: "🥛",
  },

  // Biscuits
  {
    id: 16,
    name: "Parle-G Original",
    price: "S$0.15",
    badge: "Biscuits",
    color: "from-yellow-200 to-yellow-400",
    icon: "🍪",
  },
  {
    id: 17,
    name: "Monaco Salted Biscuits",
    price: "S$0.25",
    badge: "Biscuits",
    color: "from-orange-200 to-orange-400",
    icon: "🍪",
  },
  {
    id: 18,
    name: "Good Day Cashew",
    price: "S$0.40",
    badge: "Biscuits",
    color: "from-amber-200 to-amber-400",
    icon: "🍪",
  },
  {
    id: 19,
    name: "Oreo Cookies",
    price: "S$0.55",
    badge: "Biscuits",
    color: "from-gray-600 to-gray-800",
    icon: "🍪",
  },
  {
    id: 20,
    name: "Marie Gold Biscuits",
    price: "S$0.50",
    badge: "Biscuits",
    color: "from-yellow-300 to-yellow-500",
    icon: "🍪",
  },

  // Snacks
  {
    id: 21,
    name: "Haldiram's Namkeen",
    price: "S$0.75",
    badge: "Snacks",
    color: "from-yellow-400 to-orange-500",
    icon: "🥨",
  },
  {
    id: 22,
    name: "Kurkure Masala Munch",
    price: "S$0.35",
    badge: "Snacks",
    color: "from-orange-400 to-red-500",
    icon: "🌽",
  },
  {
    id: 23,
    name: "Lay's Classic Salted",
    price: "S$0.35",
    badge: "Snacks",
    color: "from-yellow-300 to-yellow-500",
    icon: "🥔",
  },
  {
    id: 24,
    name: "Samosa (Frozen)",
    price: "S$1.30/pack",
    badge: "Ready to eat",
    color: "from-amber-300 to-amber-500",
    icon: "🥟",
  },
  {
    id: 25,
    name: "Bhujia Sev",
    price: "S$0.55",
    badge: "Snacks",
    color: "from-yellow-500 to-orange-600",
    icon: "🍜",
  },

  // Traditional/Dairy
  {
    id: 26,
    name: "Pure Desi Ghee",
    price: "S$9.50/kg",
    badge: "Traditional",
    color: "from-yellow-400 to-yellow-600",
    icon: "🧈",
  },
  {
    id: 27,
    name: "Fresh Paneer",
    price: "S$5.20/kg",
    badge: "Dairy",
    color: "from-gray-100 to-gray-300",
    icon: "🧀",
  },
  {
    id: 28,
    name: "Amul Milk 1L",
    price: "S$1.00",
    badge: "Dairy",
    color: "from-blue-200 to-blue-400",
    icon: "��",
  },
  {
    id: 29,
    name: "Curd (Dahi) 500g",
    price: "S$0.55",
    badge: "Dairy",
    color: "from-gray-100 to-gray-200",
    icon: "🥛",
  },
  {
    id: 30,
    name: "Mango Pickle",
    price: "S$2.00",
    badge: "Traditional",
    color: "from-yellow-500 to-orange-600",
    icon: "🥭",
  },

  // Grains & Pulses
  {
    id: 31,
    name: "Basmati Rice 5kg",
    price: "S$7.50",
    badge: "Grains",
    color: "from-gray-100 to-gray-300",
    icon: "🍚",
  },
  {
    id: 32,
    name: "Toor Dal 1kg",
    price: "S$2.30",
    badge: "Protein",
    color: "from-yellow-400 to-yellow-600",
    icon: "🫘",
  },
  {
    id: 33,
    name: "Chana Dal 1kg",
    price: "S$2.00",
    badge: "Protein",
    color: "from-yellow-300 to-yellow-500",
    icon: "🫘",
  },
  {
    id: 34,
    name: "Moong Dal 1kg",
    price: "S$2.10",
    badge: "Protein",
    color: "from-green-300 to-green-500",
    icon: "🫘",
  },
  {
    id: 35,
    name: "Wheat Flour 5kg",
    price: "S$3.00",
    badge: "Grains",
    color: "from-amber-200 to-amber-400",
    icon: "🌾",
  },

  // More Vegetables
  {
    id: 36,
    name: "Fresh Onions",
    price: "S$0.50/kg",
    badge: "Vegetables",
    color: "from-purple-200 to-purple-400",
    icon: "🧅",
  },
  {
    id: 37,
    name: "Ginger (Adrak)",
    price: "S$3.00/kg",
    badge: "Spicy",
    color: "from-yellow-400 to-yellow-600",
    icon: "🫚",
  },
  {
    id: 38,
    name: "Garlic (Lehsun)",
    price: "S$3.20/kg",
    badge: "Spicy",
    color: "from-gray-200 to-gray-400",
    icon: "🧄",
  },
  {
    id: 39,
    name: "Green Chili",
    price: "S$1.30/kg",
    badge: "Spicy",
    color: "from-green-400 to-green-600",
    icon: "🌶️",
  },
  {
    id: 40,
    name: "Fresh Tomatoes",
    price: "S$0.55/kg",
    badge: "Vegetables",
    color: "from-red-300 to-red-500",
    icon: "🍅",
  },

  // More Fruits
  {
    id: 41,
    name: "Sweet Oranges",
    price: "S$1.00/kg",
    badge: "Fruits",
    color: "from-orange-300 to-orange-500",
    icon: "🍊",
  },
  {
    id: 42,
    name: "Fresh Grapes",
    price: "S$1.30/kg",
    badge: "Fruits",
    color: "from-purple-300 to-purple-500",
    icon: "🍇",
  },
  {
    id: 43,
    name: "Apple (Kashmiri)",
    price: "S$2.00/kg",
    badge: "Fruits",
    color: "from-red-300 to-red-500",
    icon: "🍎",
  },
  {
    id: 44,
    name: "Watermelon",
    price: "S$0.40/kg",
    badge: "Fruits",
    color: "from-green-300 to-green-500",
    icon: "🍉",
  },
  {
    id: 45,
    name: "Sweet Lime (Mosambi)",
    price: "S$0.65/kg",
    badge: "Fruits",
    color: "from-green-200 to-green-400",
    icon: "🍋",
  },

  // More Snacks
  {
    id: 46,
    name: "Maggi Noodles",
    price: "S$0.23",
    badge: "Ready to eat",
    color: "from-yellow-400 to-orange-500",
    icon: "🍜",
  },
  {
    id: 47,
    name: "Poha (Flattened Rice)",
    price: "S$1.00/kg",
    badge: "Grains",
    color: "from-gray-100 to-gray-300",
    icon: "🍚",
  },
  {
    id: 48,
    name: "Cornflakes",
    price: "S$3.00",
    badge: "Ready to eat",
    color: "from-yellow-300 to-yellow-500",
    icon: "🥣",
  },
  {
    id: 49,
    name: "Chocos Cereal",
    price: "S$3.60",
    badge: "Sweet",
    color: "from-amber-400 to-amber-600",
    icon: "🥣",
  },
  {
    id: 50,
    name: "Mixture Namkeen",
    price: "S$0.65",
    badge: "Snacks",
    color: "from-orange-400 to-orange-600",
    icon: "🥨",
  },

  // Spices & Masalas
  {
    id: 51,
    name: "MDH Garam Masala",
    price: "S$0.75",
    badge: "Spicy",
    color: "from-red-400 to-red-600",
    icon: "🌶️",
  },
  {
    id: 52,
    name: "Turmeric Powder",
    price: "S$2.00/kg",
    badge: "Spicy",
    color: "from-yellow-500 to-yellow-700",
    icon: "🌿",
  },
  {
    id: 53,
    name: "Red Chili Powder",
    price: "S$3.00/kg",
    badge: "Spicy",
    color: "from-red-500 to-red-700",
    icon: "🌶️",
  },
  {
    id: 54,
    name: "Cumin Seeds (Jeera)",
    price: "S$5.00/kg",
    badge: "Spicy",
    color: "from-amber-500 to-amber-700",
    icon: "🌿",
  },
  {
    id: 55,
    name: "Coriander Seeds",
    price: "S$3.30/kg",
    badge: "Spicy",
    color: "from-green-400 to-green-600",
    icon: "🌿",
  },

  // More Traditional Items
  {
    id: 56,
    name: "Papad (Lijjat)",
    price: "S$0.55",
    badge: "Traditional",
    color: "from-yellow-300 to-yellow-500",
    icon: "🫓",
  },
  {
    id: 57,
    name: "Coconut Oil 1L",
    price: "S$3.00",
    badge: "Traditional",
    color: "from-gray-100 to-gray-300",
    icon: "🥥",
  },
  {
    id: 58,
    name: "Mustard Oil 1L",
    price: "S$2.30",
    badge: "Traditional",
    color: "from-yellow-500 to-yellow-700",
    icon: "🫗",
  },
  {
    id: 59,
    name: "Jaggery (Gur) 1kg",
    price: "S$1.00",
    badge: "Sweet",
    color: "from-amber-500 to-amber-700",
    icon: "🍯",
  },
  {
    id: 60,
    name: "Rock Salt (Sendha)",
    price: "S$0.65",
    badge: "Traditional",
    color: "from-gray-200 to-gray-400",
    icon: "🧂",
  },

  // More Beverages
  {
    id: 61,
    name: "Frooti Mango Drink",
    price: "S$0.25",
    badge: "Beverages",
    color: "from-orange-300 to-orange-500",
    icon: "🧃",
  },
  {
    id: 62,
    name: "Real Fruit Juice",
    price: "S$0.55",
    badge: "Beverages",
    color: "from-purple-300 to-purple-500",
    icon: "🧃",
  },
  {
    id: 63,
    name: "Nimbu Paani Mix",
    price: "S$0.40",
    badge: "Beverages",
    color: "from-green-300 to-green-500",
    icon: "🍋",
  },
  {
    id: 64,
    name: "Tata Tea Gold",
    price: "S$3.00/250g",
    badge: "Beverages",
    color: "from-amber-400 to-amber-600",
    icon: "🍵",
  },
  {
    id: 65,
    name: "Bournvita 500g",
    price: "S$4.60",
    badge: "Beverages",
    color: "from-amber-600 to-amber-800",
    icon: "☕",
  },

  // More Vegetables
  {
    id: 66,
    name: "Capsicum (Shimla Mirch)",
    price: "S$1.00/kg",
    badge: "Vegetables",
    color: "from-green-400 to-green-600",
    icon: "🫑",
  },
  {
    id: 67,
    name: "Cauliflower (Gobi)",
    price: "S$0.65/kg",
    badge: "Vegetables",
    color: "from-gray-100 to-gray-300",
    icon: "🥬",
  },
  {
    id: 68,
    name: "Cabbage (Patta Gobi)",
    price: "S$0.40/kg",
    badge: "Vegetables",
    color: "from-green-200 to-green-400",
    icon: "��",
  },
  {
    id: 69,
    name: "Potato (Aloo)",
    price: "S$0.40/kg",
    badge: "Vegetables",
    color: "from-yellow-200 to-yellow-400",
    icon: "🥔",
  },
  {
    id: 70,
    name: "Sweet Potato (Shakarkandi)",
    price: "S$0.55/kg",
    badge: "Vegetables",
    color: "from-orange-300 to-orange-500",
    icon: "🍠",
  },

  // More Dairy
  {
    id: 71,
    name: "Butter 100g",
    price: "S$0.90",
    badge: "Dairy",
    color: "from-yellow-300 to-yellow-500",
    icon: "🧈",
  },
  {
    id: 72,
    name: "Fresh Cream 200ml",
    price: "S$0.75",
    badge: "Dairy",
    color: "from-gray-100 to-gray-200",
    icon: "🥛",
  },
  {
    id: 73,
    name: "Cheese Slice",
    price: "S$2.00",
    badge: "Dairy",
    color: "from-yellow-200 to-yellow-400",
    icon: "🧀",
  },
  {
    id: 74,
    name: "Buttermilk (Chaas)",
    price: "S$0.33",
    badge: "Dairy",
    color: "from-blue-100 to-blue-300",
    icon: "🥛",
  },
  {
    id: 75,
    name: "Ice Cream (Kulfi)",
    price: "S$0.55",
    badge: "Sweet",
    color: "from-pink-300 to-pink-500",
    icon: "🍦",
  },

  // More Snacks & Ready to Eat
  {
    id: 76,
    name: "Banana Chips",
    price: "S$2.00/kg",
    badge: "Snacks",
    color: "from-yellow-400 to-yellow-600",
    icon: "🍌",
  },
  {
    id: 77,
    name: "Coconut Laddu",
    price: "S$4.00/kg",
    badge: "Sweet",
    color: "from-gray-100 to-gray-300",
    icon: "🥥",
  },
  {
    id: 78,
    name: "Gulab Jamun Mix",
    price: "S$0.75",
    badge: "Sweet",
    color: "from-amber-400 to-amber-600",
    icon: "🍯",
  },
  {
    id: 79,
    name: "Khakhras",
    price: "S$1.30",
    badge: "Snacks",
    color: "from-yellow-300 to-yellow-500",
    icon: "🍪",
  },
  {
    id: 80,
    name: "Mathri",
    price: "S$3.00/kg",
    badge: "Snacks",
    color: "from-amber-300 to-amber-500",
    icon: "🥨",
  },

  // More Grains & Pulses
  {
    id: 81,
    name: "Black Gram (Urad Dal)",
    price: "S$2.50/kg",
    badge: "Protein",
    color: "from-gray-600 to-gray-800",
    icon: "🫘",
  },
  {
    id: 82,
    name: "Kidney Beans (Rajma)",
    price: "S$2.60/kg",
    badge: "Protein",
    color: "from-red-400 to-red-600",
    icon: "🫘",
  },
  {
    id: 83,
    name: "Chickpeas (Kabuli Chana)",
    price: "S$2.00/kg",
    badge: "Protein",
    color: "from-yellow-300 to-yellow-500",
    icon: "🫘",
  },
  {
    id: 84,
    name: "Black Mustard Seeds",
    price: "S$3.00/kg",
    badge: "Spicy",
    color: "from-gray-600 to-gray-800",
    icon: "🌿",
  },
  {
    id: 85,
    name: "Fenugreek Seeds (Methi)",
    price: "S$3.60/kg",
    badge: "Spicy",
    color: "from-green-500 to-green-700",
    icon: "🌿",
  },

  // More Traditional Items
  {
    id: 86,
    name: "Hing (Asafoetida)",
    price: "S$13.00/100g",
    badge: "Spicy",
    color: "from-yellow-600 to-yellow-800",
    icon: "🌿",
  },
  {
    id: 87,
    name: "Tamarind (Imli)",
    price: "S$2.00/kg",
    badge: "Traditional",
    color: "from-amber-600 to-amber-800",
    icon: "🫐",
  },
  {
    id: 88,
    name: "Dry Coconut (Copra)",
    price: "S$3.00/kg",
    badge: "Traditional",
    color: "from-gray-100 to-gray-300",
    icon: "🥥",
  },
  {
    id: 89,
    name: "Sesame Seeds (Til)",
    price: "S$2.60/kg",
    badge: "Traditional",
    color: "from-yellow-200 to-yellow-400",
    icon: "🌿",
  },
  {
    id: 90,
    name: "Cashew Nuts",
    price: "S$13.00/kg",
    badge: "Traditional",
    color: "from-yellow-100 to-yellow-300",
    icon: "🥜",
  },

  // Last 10 Products
  {
    id: 91,
    name: "Almonds (Badam)",
    price: "S$15.00/kg",
    badge: "Traditional",
    color: "from-amber-200 to-amber-400",
    icon: "🥜",
  },
  {
    id: 92,
    name: "Raisins (Kishmish)",
    price: "S$5.80/kg",
    badge: "Sweet",
    color: "from-purple-300 to-purple-500",
    icon: "🍇",
  },
  {
    id: 93,
    name: "Dates (Khajur)",
    price: "S$4.60/kg",
    badge: "Sweet",
    color: "from-amber-500 to-amber-700",
    icon: "🫐",
  },
  {
    id: 94,
    name: "Pistachios (Pista)",
    price: "S$20.00/kg",
    badge: "Traditional",
    color: "from-green-300 to-green-500",
    icon: "🥜",
  },
  {
    id: 95,
    name: "Walnuts (Akhrot)",
    price: "S$16.00/kg",
    badge: "Traditional",
    color: "from-amber-400 to-amber-600",
    icon: "🥜",
  },
  {
    id: 96,
    name: "Fig (Anjeer)",
    price: "S$13.00/kg",
    badge: "Sweet",
    color: "from-purple-400 to-purple-600",
    icon: "🫐",
  },
  {
    id: 97,
    name: "Saffron (Kesar)",
    price: "S$41.00/100g",
    badge: "Traditional",
    color: "from-yellow-600 to-orange-600",
    icon: "🌿",
  },
  {
    id: 98,
    name: "Green Cardamom (Elaichi)",
    price: "S$30.00/kg",
    badge: "Spicy",
    color: "from-green-400 to-green-600",
    icon: "🌿",
  },
  {
    id: 99,
    name: "Cinnamon (Dalchini)",
    price: "S$10.00/kg",
    badge: "Spicy",
    color: "from-amber-500 to-amber-700",
    icon: "🌿",
  },
  {
    id: 100,
    name: "Star Anise (Chakra Phool)",
    price: "S$6.50/kg",
    badge: "Spicy",
    color: "from-amber-600 to-amber-800",
    icon: "⭐",
  },
];
